<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="18406" started-at="2019-10-01T12:43:20Z" finished-at="2019-10-01T12:43:38Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="18406" started-at="2019-10-01T12:43:20Z" finished-at="2019-10-01T12:43:38Z">
      <class name="calldoc.AppFw.Cdoc_Signup">
        <test-method status="PASS" signature="testCaseSetup()[pri:0, instance:calldoc.AppFw.Cdoc_Signup@475530b9]" name="testCaseSetup" is-config="true" duration-ms="18355" started-at="2019-10-01T18:13:20Z" finished-at="2019-10-01T18:13:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCaseSetup -->
        <test-method status="FAIL" signature="testcase1()[pri:0, instance:calldoc.AppFw.Cdoc_Signup@475530b9]" name="testcase1" duration-ms="13" started-at="2019-10-01T18:13:38Z" finished-at="2019-10-01T18:13:38Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at calldoc.AppFw.Cdoc_Signup.testcase1(Cdoc_Signup.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase1 -->
      </class> <!-- calldoc.AppFw.Cdoc_Signup -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
